---
- name: Download Curator from {{ curator_url }}
  unarchive:
    dest: /usr/local/bin
    remote_src: true
    src: "{{ curator_url }}"
    creates: /usr/local/bin/curator
  become: true

- name: Link curator binary to common places in PATH
  become: true
  file:
    state: link
    path: /usr/bin/curator
    src: /usr/local/bin/curator
  ignore_errors: true
